input.onButtonPressed(Button.AB, function () {
    pins.analogWritePin(AnalogPin.P0, 100)
    basic.pause(0o1)
    pins.analogWritePin(AnalogPin.P1, 100)
    basic.pause(0o1)
    pins.analogWritePin(AnalogPin.P2, 100)
    basic.pause(0o1)
    pins.analogWritePin(AnalogPin.P3, 100)
    basic.pause(0o1)
    pins.digitalWritePin(DigitalPin.P5, 100)
    basic.pause(0o1)
    pins.digitalWritePin(DigitalPin.P10, 100)
})
